
trigger:
- master

pool:
  vmImage: windows-2019
variables: 
 - group: new-test-var
 - name: WebAppName
   value: $[variables.asifwebapp]

steps:
- script: echo $(asifwebapp) # uses macro syntax
- script: echo $(WebAppName)

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial (19696416-07b9-4753-80aa-43befeb1ed6f)'
    subscriptionId: '19696416-07b9-4753-80aa-43befeb1ed6f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'new-var-rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'Practice-ARM/azuredeploy.json'
    csmParametersFile: 'Practice-ARM/azuredeploy.parameters.json'
    overrideParameters: '-web App Name $(WebAppName)'
    deploymentMode: 'Incremental'
